### ISSUE TITLE
Q: is this backwards compatible?

### ISSUE THREAD

**Issue by gvdhoven** [tinkerborg/thinq2-python#6] opened 2020-05-12 09:04 UTC
Would this be backwards compatible with the wideq supported devices?

Or a rephrasing of the question:
* I have now a device which is found by WideQ; i will try and see if it also will be found by your script.

Ok, result:
> No devices found!

Then i realized the country code is case sensitive (remember this from wideq); 

In the end the following gave me my valid device on latest WideQ code:
`python3 example.py -c NL -l en-NL`

```
{
    "model_info": {},
    "gateway": {
        "auth_base": "https://nl.m.lgaccount.com",
        "api_root": "https://eic.lgthinq.com:46030/api",
        "oauth_root": "https://nl.lgeapi.com",
        "country": "NL",
        "language": "en-NL"
    },
    "auth": {
        "access_token": "xxx",
        "refresh_token": "xxx"
    },
    "session": "xxx.nodes_sadap_10",
    "country": "NL",
    "language": "en-NL"
}
```

Your current code doesn't yet:
 `COUNTRY_CODE=NL LANGUAGE_CODE=en-NL poetry run python example.py`

results in:
```
{
    "auth": {
        "client_id": "3c25e7c2a38dbd839c56f03f25ea8144f3dcf5da0bbea0319e23e08bb30d875b",
        "language_code": "en-NL",
        "gateway": {
            "languageCode": "en-NL",
            "empUri": "https://nl.m.lgaccount.com",
            "thinq1Uri": "https://eic.lgthinq.com:46030/api",
            "thinq2Uri": "https://eic-service.lgthinq.com:46030/v1",
            "countryCode": "NL"
        },
        "token": {
            "expires_in": "3600",
            "access_token": "xxx",
            "refresh_token": "xxx",
            "oauth2_backend_url": "https%3A%2F%2Fgb.lgeapi.com%2F"
        },
        "profile": {
            "userNo": "xxx",
            "userID": "xxx"
        },
        "country_code": "NL"
    },
    "mqtt": {
        "ca_cert": "xxx",
        "csr": "xxx",
        "registration": {
            "subscriptions": [
                "t20/op/3c25e7c2a38dbd839c56f03f25ea8144f3dcf5da0bbea0319e23e08bb30d875b/inbox"
            ],
            "certificatePem": "xxx"
        },
        "private_key": "xxx",
        "route": {
            "mqttServer": "ssl://a3phael99lf879.iot.eu-west-1.amazonaws.com:8883",
            "apiServer": "https://eic-common.lgthinq.com:443"
        }
    }
}
```

Given the fact that the endpoints seem to match (`eic.lgthinq.com`) where can i dive in further to help getting an MQTT connection ?

**Comment by Webunity** [comment] 2020-05-12 09:57
Ok, result:
> No devices found!

Then i realized the country code is case sensitive (remember this from wideq); now it gets this error after logging in:

```
 marshmallow.exceptions.ValidationError: {'result': {'apiServer': ['Missing data for required field.'], 'mqttServer': ['Missing data for required field.']}, 'reason': ['Unknown field.']}
```

Any clue?

**Comment by Webunity** [comment] 2020-05-12 12:16
I remembered juggling with the right parameters. In the end the following gave me my valid device on latest WideQ code:
`python3 example.py -c NL -l en-NL`

However this doesn't yet: `COUNTRY_CODE=NL LANGUAGE_CODE=en-NL poetry run python example.py`

**Comment by tinkerborg** [comment] 2020-05-12 14:31
Hi, this project is not currently compatible with ThinQ v1 devices. They were specifically filtered out for now in resolution of #3. In #4 we confirmed that MQTT events are not sent for v1 devices. MQTT connections are made to an AWS IoT endpoint using a client certificate for authentication. This certificate is generated by a call to `eic-service.lgthinq.com`, which is the thinq2Uri shown in the gateway model above, while `eic.lgthinq.com` is the endpoint for the v1 API.

I haven't currently prioritized support for v1 devices as they are supported by wideq, and I don't have any v1 devices to test against anyway.

**Comment by gvdhoven** [comment] 2020-05-12 16:08
Ok, i understand, but instead 'closing the issue' i might be able to help out (as i am a software developer);

Few questions which, if answered might prevent duplicate questions in the future:
- If the client certificate is generated, wouldn't that mean that my device or account is capable of interacting over mqtt?
- How can i tell if a device is v1 or v2? E.g. if i could force my device to become v2 or something i would gladly try to re-register it; if only to stop polling for events but get realtime updates.
- I've read somewhere (i think on the original wideq thread) that new registrations are automatically v2? Or isn't that related at all?

**Comment by tinkerborg** [comment] 2020-05-12 16:19
Closing the issue isn't the same as locking it, I just closed because the initial question was answered. Collaborators are most definitely welcome for this or any other functionality!

The client certificate can be generated regardless of what devices are registered, as far as I know. I know that I created a NL account when troubleshooting another issue, and was able to create a cert with no devices registered. 

There is a `platformType` field in API responses which identifies each device as `thinq1` or `thinq2`. As to whether a device can be re-registered to use v2, I'm not really sure. I had assumed that it's just based on the device firmware and that v1 or v2 would depend on manufacture/release date. That's purely an assumption, and it would be interesting to see if an older device could be switched to v2 by simply re-registering. I only have a washer and dryer purchased last November, so I'm not sure.

**Comment by gvdhoven** [comment] 2020-05-12 16:38
Same here, i bought it also not so long ago (i have the RC90U2 dual inverter heat pump).

Re-registering it in the app (by removing it and holding the WiFi button for 3 seconds) didn't do much; still visible in wideq, and platformType still reports `thinq1`.

```
...
"platformType":"thinq1",
"regDt":20200512181350.0,
...
```

So it did re-register on LG, not just updating the WiFi locally. Maybe if i factory reset it? But i doubt it.

**Comment by stefxx** [comment] 2020-05-12 16:39
I had four a/c wall units installed recently. Three of them registered to the v1 API, and one to the v2 API. I see a complete different firmware reported between the v1 and v2 devices. If there is a way to "force" v2, I would be very interested. But honestly I don't think this is possible...

Makes you wonder if LG is willing to have 2 APIs available for an extended period of time?

**Comment by stefxx** [comment] 2020-05-12 16:40
Oh, and I tried re-registering as well. No difference.

**Comment by gvdhoven** [comment] 2020-05-12 16:40
Here is some more info; what do your v2's report?
```
         "modelName":"RC90U2_WW",
         "fwVer":"QC_Modem_1.2.79",
```

p.s. i emailed LG support with the question stating that i needed to have quicker updates in the LG app. Lets see if and how they respond.

**Comment by tinkerborg** [comment] 2020-05-12 22:34
Reopening and tagging as discussion/question until we determine if it's worth exploring further.

**Comment by gvdhoven** [comment] 2020-05-15 06:06
As expected, i got the basis reply; "We cannot comment on further updates" so i think for now this can be closed :-(

**Comment by tinkerborg** [comment] 2020-05-20 01:17
Yeah, I think it's just going to be the case that older devices will use the older API. I'll close this for now, as wideq already provides stable support for v1 devices. It could be added here, but that would most likely just be a wrapper around wideq anyway, so I don't want to lose focus on fully supporting the v2 API first.

**Closed as completed by tinkerborg** 2020-05-20 01:17 UTC
Labels: question, discussion
