### ISSUE TITLE
Error after authentication

### ISSUE THREAD

**Issue by stefxx** [tinkerborg/thinq2-python#2] opened 2020-05-07 11:47 UTC
This time I followed the instructions, and after pasting the URL this is the error I get:

Traceback (most recent call last):
  File "example.py", line 34, in <module>
    thinq = ThinQ(auth=auth)
  File "thinq2-python\thinq2\schema.py", line 89, in __init__
    self._data = schema.load(merge_args(self, args))
  File "thinq2-python\thinq2\schema.py", line 67, in merge_args
    attrs = {
  File "thinq2-python\thinq2\schema.py", line 68, in <dictcomp>
    k: getattr(self, k, None) for k in schema.fields.keys() if not k in kwargs
  File "thinq2-python\thinq2\util\__init__.py", line 10, in inner
    memo[key] = func(*args, **kwargs)
  File "thinq2-python\thinq2\schema.py", line 148, in inner
    return func(self, existing)
  File "thinq2-python\thinq2\controller\thinq.py", line 26, in mqtt
    return ThinQMQTT(mqtt, auth=self.auth)
  File "thinq2-python\thinq2\schema.py", line 89, in __init__
    self._data = schema.load(merge_args(self, args))
  File "thinq2-python\thinq2\schema.py", line 67, in merge_args
    attrs = {
  File "thinq2-python\thinq2\schema.py", line 68, in <dictcomp>
    k: getattr(self, k, None) for k in schema.fields.keys() if not k in kwargs
  File "thinq2-python\thinq2\schema.py", line 167, in inner
    value = getattr(data, obj.__name__, None) or obj(self)
  File "thinq2-python\thinq2\controller\mqtt.py", line 94, in registration
    if self.thinq_client.get_registered() is False:
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\builder.py", line 101, in __call__
    return execution.start(
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 97, in start
    return self._io.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 122, in execute
    return self._io.execute(executable)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 122, in execute
    return self._io.execute(executable)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 122, in execute
    return self._io.execute(executable)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\blocking_strategy.py", line 31, in execute
    return executable.execute()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 93, in execute
    return self.state.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 36, in execute
    return execution.before_request(self._request)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 56, in before_request
    return self.execute()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 93, in execute
    return self.state.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 105, in execute
    return execution.send(
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 73, in send
    return self._io.invoke(self._client.send, (request,), {}, callback)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 116, in invoke
    return self._io.invoke(func, args, kwargs, callback)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 116, in invoke
    return self._io.invoke(func, args, kwargs, callback)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 116, in invoke
    return self._io.invoke(func, args, kwargs, callback)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\blocking_strategy.py", line 21, in invoke
    return callback.on_success(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 96, in on_success
    return self._context.execute()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 93, in execute
    return self.state.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 123, in execute
    return execution.after_response(self._request, self._response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 62, in after_response
    return self.execute()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 93, in execute
    return self.state.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 221, in execute
    return execution.finish(self._response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 79, in finish
    return self._io.finish(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 125, in finish
    return self._io.finish(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 125, in finish
    return self._io.finish(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 143, in finish
    return self._invoke(
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 133, in _invoke
    return self._io.invoke(func, args, kwargs, FinishingCallback(self._io))
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\blocking_strategy.py", line 19, in invoke
    return callback.on_failure(type(error), error, tb)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 108, in on_failure
    return self._io.fail(exc_type, exc_val, exc_tb)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\interfaces.py", line 303, in fail
    compat.reraise(exc_type, exc_val, exc_tb)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\blocking_strategy.py", line 16, in invoke
    response = func(*arg, **kwargs)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\requests_.py", line 53, in apply_callback
    return callback(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\hooks.py", line 20, in wrapper
    return hook(*args, **kwargs)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\returns.py", line 39, in __call__
    return self._strategy(*args, **kwargs)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\converters\interfaces.py", line 6, in __call__
    return self.convert(*args, **kwargs)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\converters\marshmallow_.py", line 59, in convert
    return self._extract_data(self._schema.load(json))
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\marshmallow\schema.py", line 722, in load
    return self._do_load(
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\marshmallow\schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'status': ['Unknown field.'], 'message': ['Unknown field.'], 'timestamp': ['Unknown field.'], 'path': ['Unknown field.'], 'error': ['Unknown field.']}

**Comment by tinkerborg** [comment] 2020-05-07 14:07
Interesting - looks like the auth flow worked correctly. When bootstrapping the application state, it checks to see if the client ID it generated is registered w/ LG's API. At this point, your client isn't registered yet so it's expected that this call will error. 

It looks like the response is structured differently for you. What's your country code/language code? I've pushed a version that will give diagnostic output and exit to the `clientcheck-error` branch. What does this version display for you? For me, it's:

```
Response (400): b'{"resultCode":"0010","result":""}'
```

This could probably just check the status code and ignore the response body, but I'm curious about the difference.

**Comment by stefxx** [comment] 2020-05-07 14:16
Thanks! This is the response I am getting:

Response (404): b'{"timestamp":1588860879011,"status":404,"error":"Not Found","message":"No message available","path":"/service/users/client"}'

My account is NL/nl-NL.

**Comment by tinkerborg** [comment] 2020-05-07 14:26
OK, that explains the different message format. It's not hitting the right URL, and that's a standard 404 response from the API. The base URL comes from a call to the route.lgthinq.com API, I'm wondering if yours leaves out the /v1 prefix. I've added more debug output in the branch.

**Comment by stefxx** [comment] 2020-05-07 14:30
Thanks for your quick responses. Here is the result:

Gateway: Gateway(country_code='NL', language_code='nl-NL', thinq1_uri='https://eic.lgthinq.com:46030/api', thinq2_uri='https://eic-service.lgthinq.com:46030/v1', emp_uri='https://nl.m.lgaccount.com')
Response (404): b'{"timestamp":1588861764077,"status":404,"error":"Not Found","message":"No message available","path":"/service/users/client"}'

**Comment by tinkerborg** [comment] 2020-05-07 14:35
Hmm, that looks correct as well. Time to do the code I get paid for, but I'll look into this more after work tonight.

**Comment by tinkerborg** [comment] 2020-05-07 14:38
@stefxx You can also add the following code to the top of `example.py` to enable logging for the underlying `requests` library:

```
import logging

logging.basicConfig(level=logging.DEBUG)
```

You should see a GET request before the 404 response. Is it trying to get `https://eic-service.lgthinq.com:46030/v1/service/users/client`?

**Comment by stefxx** [comment] 2020-05-07 14:46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nl.lgeapi.com:443
DEBUG:urllib3.connectionpool:https://nl.lgeapi.com:443 "POST /oauth/1.0/oauth2/token HTTP/1.1" 200 304
Gateway: Gateway(country_code='NL', language_code='nl-NL', thinq1_uri='https://eic.lgthinq.com:46030/api', thinq2_uri='https://eic-service.lgthinq.com:46030/v1', emp_uri='https://nl.m.lgaccount.com')
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nl.lgeapi.com:443
DEBUG:urllib3.connectionpool:https://nl.lgeapi.com:443 "GET /oauth/1.0/users/profile HTTP/1.1" 200 692
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eic-service.lgthinq.com:46030
DEBUG:urllib3.connectionpool:https://eic-service.lgthinq.com:46030 "GET /service/users/client HTTP/1.1" 404 None
Response (404): b'{"timestamp":1588862736855,"status":404,"error":"Not Found","message":"No message available","path":"/service/users/client"}'

**Comment by tinkerborg** [comment] 2020-05-07 14:52
OK, it looks like it's definitely leaving out the /v1, which is weird. Will look into it tonight.

**Comment by stefxx** [comment] 2020-05-07 14:57
Thanks!

**Comment by tinkerborg** [comment] 2020-05-07 22:47
So I made an account on LG NL and it worked fine. What OS are you running this on? I suspect I may have been detrimentally lazy in the way I'm ensuring base URLs have a trailing slash...

**Comment by tinkerborg** [comment] 2020-05-07 23:30
Going to go out on a limb and say you were running this on Windows? I am on OS X and targeting Linux, and made a stupid assumption. I got a little too "cute", using `os.path.join(url, "")` to ensure base_url for the client classes ends with a trailing slash, as the uplink library expects in this case. That's not clear in intent, and leads to unexpected behavior with an OS that doesn't use `/` as pathsep. Can you try the latest code back in `master`?

**Comment by stefxx** [comment] 2020-05-08 06:13
Thanks! Yes, I am running WIndows. Using the latest code in master, this is what I get after pasting the URL:

Traceback (most recent call last):
  File "example.py", line 53, in <module>
    devices = thinq.mqtt.thinq_client.get_devices()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\builder.py", line 101, in __call__
    return execution.start(
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 97, in start
    return self._io.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 122, in execute
    return self._io.execute(executable)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 122, in execute
    return self._io.execute(executable)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 122, in execute
    return self._io.execute(executable)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\blocking_strategy.py", line 31, in execute
    return executable.execute()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 93, in execute
    return self.state.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 36, in execute
    return execution.before_request(self._request)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 56, in before_request
    return self.execute()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 93, in execute
    return self.state.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 105, in execute
    return execution.send(
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 73, in send
    return self._io.invoke(self._client.send, (request,), {}, callback)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 116, in invoke
    return self._io.invoke(func, args, kwargs, callback)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 116, in invoke
    return self._io.invoke(func, args, kwargs, callback)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 116, in invoke
    return self._io.invoke(func, args, kwargs, callback)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\blocking_strategy.py", line 21, in invoke
    return callback.on_success(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 96, in on_success
    return self._context.execute()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 93, in execute
    return self.state.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 123, in execute
    return execution.after_response(self._request, self._response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 62, in after_response
    return self.execute()
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 93, in execute
    return self.state.execute(self)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\state.py", line 221, in execute
    return execution.finish(self._response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 79, in finish
    return self._io.finish(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 125, in finish
    return self._io.finish(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 125, in finish
    return self._io.finish(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 143, in finish
    return self._invoke(
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 133, in _invoke
    return self._io.invoke(func, args, kwargs, FinishingCallback(self._io))
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\blocking_strategy.py", line 19, in invoke
    return callback.on_failure(type(error), error, tb)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\execution.py", line 108, in on_failure
    return self._io.fail(exc_type, exc_val, exc_tb)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\interfaces.py", line 303, in fail
    compat.reraise(exc_type, exc_val, exc_tb)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\io\blocking_strategy.py", line 16, in invoke
    response = func(*arg, **kwargs)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\clients\requests_.py", line 53, in apply_callback
    return callback(response)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\hooks.py", line 20, in wrapper
    return hook(*args, **kwargs)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\returns.py", line 39, in __call__
    return self._strategy(*args, **kwargs)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\converters\interfaces.py", line 6, in __call__
    return self.convert(*args, **kwargs)
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\uplink\converters\marshmallow_.py", line 59, in convert
    return self._extract_data(self._schema.load(json))
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\marshmallow\schema.py", line 722, in load
    return self._do_load(
  File "pypoetry\Cache\virtualenvs\thinq2-i1Pm4NnS-py3.8\lib\site-packages\marshmallow\schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'result': {'item': {0: {'area': ['Missing data for required field.'], 'userNo': ['Missing data for required field.'], 'blackboxYn': ['Missing data for required field.'], 'snapshot': ['Missing data for required field.'], 'countryCode': ['Missing data for required field.'], 'modelCountryCode': ['Missing data for required field.']}, 1: {'area': ['Missing data for required field.'], 'userNo': ['Missing data for required field.'], 'blackboxYn': ['Missing data for required field.'], 'snapshot': ['Missing data for required field.'], 'countryCode': ['Missing data for required field.'], 'modelCountryCode': ['Missing data for required field.']}, 2: {'area': ['Missing data for required field.'], 'userNo': ['Missing data for required field.'], 'blackboxYn': ['Missing data for required field.'], 'snapshot': ['Missing data for required field.'], 'countryCode': ['Missing data for required field.'], 'modelCountryCode': ['Missing data for required field.']}}}}

**Comment by tinkerborg** [comment] 2020-05-08 12:43
Interesting, based on this and the other issue I'm wondering how consistent the responses are from the "dashboard" endpoint. What kind of devices are these?

I've changed the `example.py` to write out application state immediately after auth, so you shouldn't have to keep going through the OAuth flow.

Can you try running the code from the `thinq-log` branch? This should log the raw response body from the `get_devices()` call.

**Comment by stefxx** [comment] 2020-05-08 13:10
Thanks! I just ran the -log version. There is quite some information that I am not sure I want to post here publicly. But I think I see the problem. When you call service/application/dashboard I am getting both v1 and v2 devices back (I have 4 AC units, only one is v2). The v1 devices have a lot less information. You can filter them by the "platformType" field. For v1 devices there is no "snapshot", "fwInfoList" and "modemInfo" information.

If I can send you the JSON privately let me know.

**Comment by tinkerborg** [comment] 2020-05-08 14:32
OK, this makes sense. I only have the new washer/dryer and don't have any V1 devices to test with, so it wouldn't have cropped up for me. The initial bug is fixed, and this looks like the same problem as #3, so I'll close this one and we can follow up there for this issue.

**Closed as completed by tinkerborg** 2020-05-08 14:32 UTC
